# Travis CI integration
# Defaults to GNU GCC and autotools: ./configure && make && make test
language: c
cache: ccache

# Use docker for quicker builds, it now allows https://docs.travis-ci.com/user/apt/
sudo: false

# Test build with both GCC and Clang (LLVM)
# XXX: REMEMBER TO DISABLE CLANG WHEN RUNNING CONVERITY SCAN
# XXX: https://github.com/travis-ci/travis-ci/issues/1975
compiler:
  - gcc
  - clang

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "BOySKarfB7ySP4SQ9vpeLz/Yrle3cxGYe+f5ep6OVk42M2bmonX27FdgVF5oKpII6Sq5hXrhoNrwRpkYRj+G5OUy4lguOALJ1AAtRpvlrfXCCL5Vxe9TDBNpmU/AfOcZoiGiR5Vpv96CIIoqvnB6XQJMMfTa2JHvU7tZCS2p9lU="

addons:
  apt:
    packages:
      - tree
      - libcap-dev
      - cppcheck
  coverity_scan:
    project:
      name: "troglobit/smcroute"
      description: "SMCRoute -- Static Multicast Routing Daemon"
    notification_email: troglobit@gmail.com
    build_command_prepend: ./autogen.sh && ./configure
    build_command: make -j5 clean all
    branch_pattern: dev

# We don't store generated files (configure and Makefile) in GIT,
# so we must customize the default build script to run ./autogen.sh
script:
  - cppcheck -j2 src/
  - ./autogen.sh
  - ./configure --disable-silent-rules --enable-mrdisc --prefix=
  - make clean
  - make -j5
  - make
  - DESTDIR=~/tmp make install-strip
  - tree ~/tmp
  - ldd ~/tmp/sbin/smcrouted
  - size ~/tmp/sbin/smcrouted
  - ldd ~/tmp/sbin/smcroutectl
  - size ~/tmp/sbin/smcroutectl
  - ~/tmp/sbin/smcrouted -h
  - ~/tmp/sbin/smcroutectl -h
