#!/bin/sh
# Compatibility wrapper for users with old startup scripts
# Written by Joachim Nilsson, placed in the public domain

OP=$1
shift

case "$OP" in
    -d)
	smcrouted $*
	;;
    -h)
	echo "This is a simple compatibility wrapper script for SMCRoute intended"
	echo "for use with old style startup scripts.  Use the /etc/smcroute.conf"
	echo "configuration file instead, see the smcroute(8) man page for help."
	return 0
	;;
    -k)
	smcroutectl kill
	;;
    -v)
	smcroutectl version
	;;
    -a)
	smcroutectl add $*
	;;
    -r)
	smcroutectl remove $*
	;;
    -j)
	smcroutectl join $*
	;;
    *)
	echo "Unkown command or option to the SMCRoute compatiblity wrapper script."
	echo "See the smcroute(8) man page for help on available commands."
	return 1
	;;
esac
