.\"                                      Hey, EMACS: -*- nroff -*-
.TH MCSENDER 8 "June 1, 2006"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
mcsender \- Multicast test tool to send multicast test packets
.SH SYNOPSIS
.B mcsender \fP[\fB-t\fP\fI<ttl>\fP] \fBip:port\fP

.SH DESCRIPTION

\fBmcsender\fP sends multicast packets to the specified ip address and
port. The packets sent contain the string "this is the test message
from mclab/mcsender\\n".

.SH OPTIONS

.TP
.B -t\fI<ttl>\fP
Set the TTL to the specified value.

.SH AUTHOR
mcsender was written by Carsten Schill <carsten@cschill.de>.
.PP
This manual page was written by Julien BLACHE <jblache@debian.org>,
for the Debian project (but may be used by others).
